language: python
python:
    - "3.6"
install:
    - pip install -r requirements.txt
script:
    - py.test --cov-report term-missing --cov=transformers
branches:
    only:
        - master
after_success:
    - coveralls